import React from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, Play, Star, CheckCircle2, BookOpen, Stethoscope, Users, Menu, X } from 'lucide-react';
import './styles.css';

const courses=[['PLAB 1','A focused, exam-first pathway for doctors preparing for PLAB 1.','Learn more'],['PLAB 2','Structured preparation, clinical scenarios and practical guidance for PLAB 2.','Explore PLAB 2'],['UK Medical Career','Practical guidance for doctors building a career and life in the UK.','See the pathway']];

function App(){const [open,setOpen]=React.useState(false);return <div className="app">
<header><div className="nav wrap"><div className="brand"><span>DR MO</span><small>SOBHY ACADEMY</small></div><button className="menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?'show':''}><a href="#academy">Academy</a><a href="#courses">Courses</a><a href="#about">About Dr Mo</a><a href="#results">Why us</a><a className="navcta" href="#courses">Explore courses <ArrowRight size={16}/></a></nav></div></header>
<main>
<section className="hero"><div className="wrap heroGrid"><div className="heroCopy"><div className="eyebrow"><span></span> Medical education. Made practical.</div><h1>Build your medical career in the <em>UK.</em></h1><p>Clear, structured guidance and exam preparation from a doctor who has walked the path himself.</p><div className="actions"><a className="primary" href="#courses">Explore the Academy <ArrowRight size={18}/></a><a className="secondary" href="#about"><Play size={16} fill="currentColor"/> Meet Dr Mo</a></div><div className="proof"><div className="avatars"><i>1</i><i>2</i><i>3</i><i>+</i></div><div><strong>Thousands of doctors</strong><span>trust Dr Mo's teaching</span></div></div></div><div className="heroVisual"><div className="portrait"><div className="portraitText">DR<br/>MO</div></div><div className="floating cardTop"><Star size={16} fill="currentColor"/><b>Trusted by doctors</b><span>Across the UK & beyond</span></div><div className="floating cardBottom"><CheckCircle2 size={18}/><span>Structured learning</span></div></div></div></section>
<section className="stats"><div className="wrap statsGrid"><div><b>30K+</b><span>Instagram community</span></div><div><b>10+</b><span>Years in medicine</span></div><div><b>3</b><span>Core pathways</span></div><div><b>UK</b><span>Doctor-led education</span></div></div></section>
<section id="academy" className="intro wrap"><div><div className="eyebrow"><span></span> The Academy</div><h2>Everything you need to move forward with confidence.</h2></div><p>Whether you're preparing for a medical licensing exam or planning your next step in the UK, the Academy brings practical teaching, proven frameworks and real-world experience together in one place.</p></section>
<section id="courses" className="courses wrap"><div className="sectionHead"><div><div className="eyebrow"><span></span> Learn with Dr Mo</div><h2>Choose your pathway.</h2></div><a href="#courses">View all <ArrowRight size={16}/></a></div><div className="courseGrid">{courses.map((c,i)=><article className={i===0?'featured':''} key={c[0]}><div className="courseIcon">{i===0?<Stethoscope/>:i===1?<BookOpen/>:<Users/>}</div><span className="courseNo">0{i+1}</span><h3>{c[0]}</h3><p>{c[1]}</p><a href="#contact">{c[2]} <ArrowRight size={15}/></a></article>)}</div></section>
<section id="about" className="about"><div className="wrap aboutGrid"><div className="aboutPhoto"><span>DR MO<br/><small>DOCTOR • EDUCATOR • ENTREPRENEUR</small></span></div><div><div className="eyebrow"><span></span> Meet Dr Mo</div><h2>A doctor. An educator. A guide for the journey.</h2><p>Dr Mohamed Fathelbab is an Egyptian-British doctor, GP trainee and founder of Dr Mo Sobhy Academy. His mission is simple: make the path to practising medicine in the UK clearer, more structured and less overwhelming.</p><p>The Academy combines medical expertise with practical, experience-led education designed around what doctors actually need.</p><a className="textLink" href="#contact">Learn more about Dr Mo <ArrowRight size={16}/></a></div></div></section>
<section id="results" className="results wrap"><div className="resultQuote"><div className="stars">★★★★★</div><blockquote>“The goal isn't just to pass an exam. It's to help you become the doctor you want to be.”</blockquote><span>DR MO SOBHY • FOUNDER</span></div><div className="resultCards"><div><b>01</b><h3>Clear teaching</h3><p>No unnecessary noise. Learn what matters and why.</p></div><div><b>02</b><h3>Real experience</h3><p>Guidance shaped by the realities of UK medical training.</p></div><div><b>03</b><h3>A community</h3><p>You're not navigating the journey alone.</p></div></div></section>
<section id="contact" className="cta"><div className="wrap"><div className="eyebrow light"><span></span> Start your journey</div><h2>Ready for your next step?</h2><p>Explore the Academy and find the pathway that fits where you are now.</p><a className="lightBtn" href="#courses">Explore courses <ArrowRight size={18}/></a></div></section>
</main><footer><div className="wrap footer"><div className="brand"><span>DR MO</span><small>SOBHY ACADEMY</small></div><span>Medical education for doctors building their future in the UK.</span><span>© 2026 Dr Mo Sobhy Academy</span></div></footer></div>}
createRoot(document.getElementById('root')).render(<App/>);
