import React from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, Play, Star, CheckCircle2, BookOpen, Stethoscope, Menu, X, MapPin, MessageCircle, ClipboardCheck } from 'lucide-react';
import './styles.css';

const pathways=[
  ['PLAB 2 Academy','Structured preparation for the practical, clinical and communication demands of PLAB 2.','Explore PLAB 2',Stethoscope],
  ['Mock practice','Repeat stations, practise under pressure and use feedback to sharpen your performance.','See the approach',ClipboardCheck],
  ['Study resources','Structured teaching notes and learning resources to support your preparation.','Explore resources',BookOpen]
];
const faqs=[
 ['What is PLAB 2?','PLAB 2 is the practical clinical assessment in the PLAB route for doctors seeking registration to practise medicine in the UK.'],
 ['Where is the academy?','Dr Mo Sobhy Academy is based in Crewe, Cheshire, in the UK.'],
 ['Who is the academy for?','The academy is primarily aimed at international medical graduates preparing for PLAB 2 and their transition towards UK practice.'],
 ['How do I enquire?','Use the Academy social channels or direct contact details supplied by the academy for current course dates, availability and fees.']
];
function App(){
 const [open,setOpen]=React.useState(false); const [faq,setFaq]=React.useState(null);
 return <div className="app">
 <header><div className="nav wrap"><div className="brand"><span>DR MO</span><small>SOBHY ACADEMY</small></div><button className="menu" aria-label="Open menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?'show':''}><a href="#academy">Academy</a><a href="#courses">PLAB 2</a><a href="#experience">How it works</a><a href="#about">About Dr Mo</a><a className="navcta" href="#contact">Enquire <ArrowRight size={16}/></a></nav></div></header>
 <main>
 <section className="hero"><div className="wrap heroGrid"><div className="heroCopy"><div className="eyebrow"><span></span> PLAB 2 preparation</div><h1>Prepare with purpose. <em>Practise</em> with confidence.</h1><p>Dr Mo Sobhy Academy is a UK-based medical education academy focused on helping international doctors prepare for PLAB 2 through structured teaching, practical practice and an experienced learning community.</p><div className="actions"><a className="primary" href="#courses">Explore the Academy <ArrowRight size={18}/></a><a className="secondary" href="#about"><Play size={16} fill="currentColor"/> Meet Dr Mo</a></div><div className="proof"><div className="avatars"><i>PLAB</i><i>2</i><i>UK</i><i>+</i></div><div><strong>Built around the PLAB 2 journey</strong><span>for doctors working towards UK practice</span></div></div></div><div className="heroVisual"><div className="portrait"><div className="portraitText">DR<br/>MO</div></div><div className="floating cardTop"><Star size={16} fill="currentColor"/><b>PLAB 2 focused</b><span>Clinical, practical & communication preparation</span></div><div className="floating cardBottom"><CheckCircle2 size={18}/><span>Practise. Reflect. Improve.</span></div></div></div></section>
 <section className="stats"><div className="wrap statsGrid"><div><b>30K+</b><span>Instagram community</span></div><div><b>PLAB 2</b><span>Core academy focus</span></div><div><b>UK</b><span>Doctor-led education</span></div><div><b>CREWE</b><span>Academy base</span></div></div></section>
 <section id="academy" className="intro wrap"><div><div className="eyebrow"><span></span> The Academy</div><h2>A preparation environment built around the practical side of the exam.</h2></div><p>Public student experiences describe Dr Mo Sobhy Academy as a place for structured PLAB 2 preparation, mock practice, teaching and peer practice. Independent reviews and videos also show an established academy with an international student community.</p></section>
 <section id="courses" className="courses wrap"><div className="sectionHead"><div><div className="eyebrow"><span></span> Learn with Dr Mo</div><h2>Prepare around the skills that matter.</h2></div><a href="#contact">Enquire now <ArrowRight size={16}/></a></div><div className="courseGrid">{pathways.map(([title,desc,link,Icon],i)=><article className={i===0?'featured':''} key={title}><div className="courseIcon"><Icon/></div><span className="courseNo">0{i+1}</span><h3>{title}</h3><p>{desc}</p><a href="#contact">{link} <ArrowRight size={15}/></a></article>)}</div></section>
 <section id="experience" className="experience"><div className="wrap experienceGrid"><div><div className="eyebrow"><span></span> The preparation model</div><h2>Move from knowing the material to performing it.</h2><p className="sectionLead">PLAB 2 is practical. Your preparation should be practical too.</p></div><div className="experienceList"><div><b>01</b><span><strong>Clinical scenarios</strong> Build familiarity with patient-facing scenarios and structured clinical encounters.</span></div><div><b>02</b><span><strong>Communication & IPS</strong> Practise the communication and interpersonal skills that sit at the heart of clinical encounters.</span></div><div><b>03</b><span><strong>Mock practice</strong> Rehearse stations repeatedly, learn to work under time pressure and use feedback to improve.</span></div><div><b>04</b><span><strong>Teaching & resources</strong> Support your practice with structured teaching and academy learning materials.</span></div></div></div></section>
 <section className="socialProof"><div className="wrap"><div className="sectionHead"><div><div className="eyebrow"><span></span> Student perspective</div><h2>A name doctors actively compare when choosing PLAB 2 preparation.</h2></div></div><div className="proofGrid"><div><div className="stars">★★★★★</div><p>Mo Sobhy 100%.</p><span>PLABprep community discussion, 2025</span></div><div><div className="stars">★★★★★</div><p>I found it helpful throughout my PLAB 2 journey.</p><span>PLABprep community discussion, 2025</span></div><div><div className="stars">★★★★★</div><p>Independent PLAB 2 reviews describe structured notes, teaching and practical mock preparation.</p><span>Public student review sources</span></div></div><small className="sourceNote">Public-source summaries only. These are not official academy testimonials.</small></div></section>
 <section id="about" className="about"><div className="wrap aboutGrid"><div className="aboutPhoto"><span>DR MO<br/><small>DOCTOR • EDUCATOR • ENTREPRENEUR</small></span></div><div><div className="eyebrow"><span></span> Meet Dr Mo</div><h2>A doctor who turned his experience into an academy for international doctors.</h2><p>Dr Mohamed Sobhy Abdelgayed Tohamy Fathelbab is the founder and director behind Dr Mo Teaching Academy Ltd, an active UK education company based in Crewe. UK company records show him as the person with 75% or more of the shares and voting rights.</p><p>The academy's public footprint is strongly associated with PLAB 2 preparation, educational resources and an international community of doctors working towards UK practice.</p><a className="textLink" href="#contact">Connect with the Academy <ArrowRight size={16}/></a></div></div></section>
 <section className="faq"><div className="wrap faqGrid"><div><div className="eyebrow"><span></span> Frequently asked</div><h2>Before you start.</h2><p>Course dates, fees and availability can change, so confirm the current details directly with the Academy.</p></div><div>{faqs.map(([q,a],i)=><div className="faqItem" key={q}><button onClick={()=>setFaq(faq===i?null:i)}><span>{q}</span><b>{faq===i?'−':'+'}</b></button>{faq===i&&<p>{a}</p>}</div>)}</div></div></section>
 <section id="contact" className="contact"><div className="wrap contactGrid"><div><div className="eyebrow"><span></span> Find the Academy</div><h2>Ready to take the next step?</h2><p>For current course dates, fees, availability and enrolment, contact the Academy directly through its current official channels.</p><div className="contactActions"><a className="primary" href="https://www.instagram.com/drmosobhy/" target="_blank" rel="noreferrer"><MessageCircle size={17}/> Instagram</a></div></div><div className="location"><MapPin/><div><strong>Crewe, Cheshire</strong><span>Dr Mo Sobhy Academy</span><small>United Kingdom</small></div></div></div></section>
 <section className="cta"><div className="wrap"><div className="eyebrow light"><span></span> Your PLAB 2 journey</div><h2>Prepare for the room, not just the notes.</h2><p>Explore the Academy and find the preparation approach that fits your journey.</p><a className="lightBtn" href="#contact">Enquire about the Academy <ArrowRight size={18}/></a></div></section>
 </main><footer><div className="wrap footer"><div className="brand"><span>DR MO</span><small>SOBHY ACADEMY</small></div><span>PLAB 2 preparation & medical education.</span><span>© 2026 Dr Mo Sobhy Academy</span></div></footer></div>
}
createRoot(document.getElementById('root')).render(<App/>);
