import React from 'react';
import { ArrowRight, Play, CheckCircle2, BookOpen, Stethoscope, Menu, X, MapPin, MessageCircle, ClipboardCheck, ExternalLink, Send } from 'lucide-react';
import './styles.css';

const pathways=[
  ['PLAB 2 Academy','Structured preparation for the practical, clinical and communication demands of PLAB 2.','Start with the Academy',Stethoscope],
  ['Mock practice','Repeat stations, practise under pressure and use feedback to sharpen your performance.','Ask about mocks',ClipboardCheck],
  ['Study resources','Structured teaching notes and learning resources to support your preparation.','Ask about resources',BookOpen]
];
const faqs=[
  ['What is PLAB 2?','PLAB 2 is the practical clinical assessment in the PLAB route for doctors seeking registration to practise medicine in the UK.'],
  ['Where is the academy?','Dr Mo Sobhy Academy is based in Crewe, Cheshire, in the UK.'],
  ['Who is the academy for?','The academy is primarily aimed at international medical graduates preparing for PLAB 2 and their transition towards UK practice.'],
  ['How do I enquire?','Tell the Academy where you are in your preparation, then confirm current dates, availability and fees directly with the Academy.']
];
const heroImage='https://img.youtube.com/vi/E_Y9iSWMNzk/maxresdefault.jpg';
const secondImage='https://img.youtube.com/vi/IAXc4oqTq6c/maxresdefault.jpg';
function App(){
 const [open,setOpen]=React.useState(false); const [faq,setFaq]=React.useState(null); const [sent,setSent]=React.useState(false);
 const submit=e=>{e.preventDefault();setSent(true)};
 return <div className="app">
 <header><div className="nav wrap"><div className="brand"><span>DR MO</span><small>SOBHY ACADEMY</small></div><button className="menu" aria-label="Open menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?'show':''}><a href="#academy">Academy</a><a href="#courses">PLAB 2</a><a href="#experience">How it works</a><a href="#about">About Dr Mo</a><a className="navcta" href="#contact">Enquire <ArrowRight size={16}/></a></nav></div></header>
 <main>
 <section className="hero"><div className="wrap heroGrid"><div className="heroCopy"><div className="eyebrow"><span></span> PLAB 2 preparation</div><h1>Prepare with purpose. <em>Practise</em> with confidence.</h1><p>Dr Mo Sobhy Academy is a UK-based medical education academy focused on helping international doctors prepare for PLAB 2 through structured teaching, practical practice and an experienced learning community.</p><div className="actions"><a className="primary" href="#courses">Find your preparation route <ArrowRight size={18}/></a><a className="secondary" href="#watch"><Play size={16} fill="currentColor"/> Watch the academy</a></div><div className="proof"><div className="avatars"><i>PLAB</i><i>2</i><i>UK</i><i>+</i></div><div><strong>Built around the PLAB 2 journey</strong><span>for doctors working towards UK practice</span></div></div></div><div className="heroVisual"><div className="heroFrame"><img src={heroImage} alt="PLAB 2 candidate experience at Dr Mo Sobhy Academy"/><div className="imageShade"></div><a className="heroPlay" href="https://www.youtube.com/watch?v=E_Y9iSWMNzk" target="_blank" rel="noreferrer"><Play size={19} fill="currentColor"/></a><div className="heroCaption"><span>THE ACADEMY</span><strong>Inside the PLAB 2 experience</strong></div></div><div className="miniFrame"><img src={secondImage} alt="Candidate review of Dr Mo Sobhy Academy"/><span><Play size={13} fill="currentColor"/></span></div><div className="floating cardTop"><CheckCircle2 size={16}/><b>PLAB 2 focused</b><span>Clinical, practical & communication preparation</span></div><div className="floating cardBottom"><CheckCircle2 size={18}/><span>Practise. Reflect. Improve.</span></div></div></div></section>
 <section className="stats"><div className="wrap statsGrid"><div><b>29K+</b><span>Instagram community</span></div><div><b>PLAB 2</b><span>Core academy focus</span></div><div><b>UK</b><span>Doctor-led education</span></div><div><b>CREWE</b><span>Academy base</span></div></div></section>
 <section id="academy" className="intro wrap"><div><div className="eyebrow"><span></span> The Academy</div><h2>A preparation environment built around the practical side of the exam.</h2></div><p>Public student experiences describe Dr Mo Sobhy Academy as a place for structured PLAB 2 preparation, mock practice, teaching and peer practice. Independent reviews and videos also show an established academy with an international student community.</p></section>
 <section id="courses" className="courses wrap"><div className="sectionHead"><div><div className="eyebrow"><span></span> Learn with Dr Mo</div><h2>Choose the kind of preparation you need.</h2></div><a href="#contact">Enquire now <ArrowRight size={16}/></a></div><div className="courseGrid">{pathways.map(([title,desc,link,Icon],i)=><article className={i===0?'featured':''} key={title}><div className="courseIcon"><Icon/></div><span className="courseNo">0{i+1}</span><h3>{title}</h3><p>{desc}</p><a href="#contact">{link} <ArrowRight size={15}/></a></article>)}</div></section>
 <section id="experience" className="experience"><div className="wrap experienceGrid"><div><div className="eyebrow"><span></span> A practical preparation rhythm</div><h2>Turn preparation into performance.</h2><p className="sectionLead">Use the Academy experience to complement your own study, practise deliberately and identify where you need more confidence.</p></div><div className="experienceList"><div><b>01</b><span><strong>Build your foundation</strong> Arrive with the core knowledge you need, then use practical sessions to turn theory into action.</span></div><div><b>02</b><span><strong>Practise the encounter</strong> Work through clinical scenarios, communication and interpersonal skills with other candidates.</span></div><div><b>03</b><span><strong>Pressure-test your stations</strong> Use mock practice to rehearse timing, structure and decision-making under exam conditions.</span></div><div><b>04</b><span><strong>Refine the weak points</strong> Use feedback and repeated practice to focus the final part of your preparation where it matters most.</span></div></div></div></section>
 <section id="watch" className="watch"><div className="wrap"><div className="sectionHead"><div><div className="eyebrow"><span></span> See the experience</div><h2>Hear from candidates who have been there.</h2></div><span className="watchLabel">Public videos • external sources</span></div><div className="videoGrid"><a className="videoCard" href="https://www.youtube.com/watch?v=E_Y9iSWMNzk" target="_blank" rel="noreferrer"><div className="videoThumb"><img src={heroImage} alt="One Week in Dr Mo Sobhy Academy"/><span><Play fill="currentColor"/></span></div><div className="videoMeta"><strong>One Week in Dr Mo Sobhy Academy</strong><small>PLAB 2 candidate experience • 2024</small><ExternalLink size={15}/></div></a><a className="videoCard" href="https://www.youtube.com/watch?v=IAXc4oqTq6c" target="_blank" rel="noreferrer"><div className="videoThumb"><img src={secondImage} alt="Reviewing Dr Mo Sobhy Academy"/><span><Play fill="currentColor"/></span></div><div className="videoMeta"><strong>Reviewing Dr Mo Sobhy Academy</strong><small>Candidate review • 2023</small><ExternalLink size={15}/></div></a></div></div></section>
 <section className="socialProof"><div className="wrap"><div className="sectionHead"><div><div className="eyebrow"><span></span> Student perspective</div><h2>A name doctors actively compare when choosing PLAB 2 preparation.</h2></div></div><div className="proofGrid"><div><span className="proofTag">FACE-TO-FACE</span><p>Public PLAB discussions include candidates who recommend the academy for in-person review and practical preparation.</p><span>Public PLAB community discussion • 2024</span></div><div><span className="proofTag">PRACTICE</span><p>Some candidates specifically highlight repeated clinical practice, mocks and peer sessions as useful parts of their preparation.</p><span>Public PLAB community discussion • 2024</span></div><div><span className="proofTag">TRANSPARENCY</span><p>Other public discussions raise concerns about price and consistency, making clear programme details and expectations important.</p><span>Public PLAB community discussion • 2025</span></div></div><small className="sourceNote">Public-source summaries only. These are not official academy testimonials or ratings.</small></div></section>
 <section id="about" className="about"><div className="wrap aboutGrid"><div className="aboutPhoto"><div className="aboutVisual"><img src={secondImage} alt="Dr Mo Sobhy Academy candidate experience"/><div className="aboutBadge">UK<br/><b>ACADEMY</b></div></div></div><div><div className="eyebrow"><span></span> Meet Dr Mo</div><h2>A doctor who turned his experience into an academy for international doctors.</h2><p>Dr Mohamed Sobhy Abdelgayed Tohamy Fathelbab is the founder and director behind Dr Mo Teaching Academy Ltd, an active UK education company based in Crewe. UK company records show him as the person with 75% or more of the shares and voting rights.</p><p>The academy's public footprint is strongly associated with PLAB 2 preparation, educational resources and an international community of doctors working towards UK practice.</p><a className="textLink" href="#contact">Connect with the Academy <ArrowRight size={16}/></a></div></div></section>
 <section className="faq"><div className="wrap faqGrid"><div><div className="eyebrow"><span></span> Frequently asked</div><h2>Before you start.</h2><p>Course dates, fees and availability can change, so confirm the current details directly with the Academy.</p></div><div>{faqs.map(([q,a],i)=><div className="faqItem" key={q}><button onClick={()=>setFaq(faq===i?null:i)}><span>{q}</span><b>{faq===i?'−':'+'}</b></button>{faq===i&&<p>{a}</p>}</div>)}</div></div></section>
 <section id="contact" className="contact"><div className="wrap contactGrid"><div><div className="eyebrow"><span></span> Enquire</div><h2>Tell the Academy where you are in your PLAB 2 journey.</h2><p>Start with three details: what you are preparing for, when your exam is, and what kind of support you are looking for. Current dates, fees and availability should then be confirmed directly with the Academy.</p><div className="location"><MapPin size={16}/><span>Crewe, Cheshire, UK</span></div><a className="secondary socialButton" href="https://www.instagram.com/drmosobhy/" target="_blank" rel="noreferrer"><MessageCircle size={17}/> Instagram</a></div><div className="enquiryBox">{sent?<div className="success"><CheckCircle2 size={34}/><h3>Thanks — your enquiry is ready.</h3><p>This prototype confirms the interaction only. Before launch, connect the form to the Academy's preferred email, CRM or WhatsApp workflow.</p><button className="primary" onClick={()=>setSent(false)}>Start another enquiry</button></div>:<form onSubmit={submit}><div className="formRow"><label>Name<input required name="name" placeholder="Your name"/></label><label>Email<input required type="email" name="email" placeholder="you@example.com"/></label></div><div className="formRow"><label>WhatsApp<input name="whatsapp" placeholder="Optional"/></label><label>Exam date<input name="examDate" type="date"/></label></div><label>Where are you in your preparation?<input required name="stage" placeholder="e.g. just passed PLAB 1 / revising / exam booked"/></label><label>What are you looking for?<input required name="preparation" placeholder="e.g. academy, mocks, clinical practice"/></label><label>Message<textarea name="message" rows="4" placeholder="Anything else the Academy should know?"></textarea></label><button className="primary" type="submit"><Send size={16}/> Request course details</button><small>Demo form • no data is submitted from this prototype.</small></form>}</div></div></section>
 <section className="cta"><div className="wrap"><div className="eyebrow light"><span></span> Your PLAB 2 journey</div><h2>Prepare for the room, not just the notes.</h2><p>Explore the Academy and find the preparation approach that fits your journey.</p><a className="lightBtn" href="#contact">Enquire about the Academy <ArrowRight size={18}/></a></div></section>
 </main><footer><div className="wrap footer"><div className="brand"><span>DR MO</span><small>SOBHY ACADEMY</small></div><span>PLAB 2 preparation & medical education.</span><span>© 2026 Dr Mo Sobhy Academy</span></div></footer></div>
}
createRoot(document.getElementById('root')).render(<App/>);
